version: '2.3'

services:
  database:
    image: mysql:8.0
    container_name: mysql_db_library_system
    env_file: .env
    ports:
      - "3310:3306"
    volumes:
      - mysql_data3:/var/lib/mysql
volumes:
  mysql_data3: